import streamlit
streamlit.title('My breakkie')
streamlit.text('Scrambled eggs')
streamlit.text('Avocado & Cheese')
streamlit.text('Porridge')
streamlit.title('My Parents New Healthy Diner')
streamlit.header('Breakfast Menu')
streamlit.text('Omega 3 & Blueberry Oatmeal')
streamlit.text('Kale, Spinach & Rocket Smoothie')
streamlit.text('Hard-Boiled Free-Range Egg')
